### PR TITLE
Correct Russian translation and tz-hint for Shymkent

### PR DESCRIPTION
**Pull request by rezso**
Reported on G+ by Михаил Дружинин

### CODE REVIEW

**Comment by raveit65** [comment]
Translations updates you need to do this on Transiflex web page.
https://www.transifex.com/
Create a account there and become a member of russian Mate translation theme.
Changes on po files we can't do here.

**Comment by rezso** [comment]
I cannot find the po files for po-locations on transifex. Just the „normal” po files. Sorry.

**Comment by monsta** [comment]
Wait, I think we still don't have these locations on Transifex...

**Comment by rezso** [comment]
In addition, not configured in .tx/config file...

**Comment by monsta** [comment]
Ok, merged.

**Pull request merged**
