### PR TITLE
use TLS certificate verification for libsoup session

### PR DESCRIPTION
**Pull request by raveit65**
partially fix for https://github.com/mate-desktop/libmateweather/issues/96

### CODE REVIEW

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Can anyone please review this PR please?

**Review by mbkma — APPROVED** [review]
mate-weather-applet and mate-clock-applet work as before. From the documentation this should be the correct fix for #96  (https://developer.gnome.org/libsoup/stable/SoupSession.html#SoupSession--ssl-use-system-ca-file).
However a proper fix is needed (porting to SoupSession or replacing libmateweather with libgweather which is WIP https://github.com/mate-desktop/mate-panel/pull/1075).

The irc freenode link in travis is also updated to libera.

**Review by vkareh — APPROVED** [review]
LGTM

**Comment by lukefromdc** [comment]
I was able to add and remove a location in the clock applet without issue with this, so seems to be fine with Debian Unstable as of 7-10-2021

**Comment by raveit65** [comment]
> I was able to add and remove a location in the clock applet without issue with this, so seems to be fine with Debian Unstable as of 7-10-2021

Why should this be a problem?
The problem with clock-applet was caused by using `soup_session_new ` to fix deprecated `soup_session_async_new`.
This needs to be done for libsoup3.

**Comment by lukefromdc** [comment]
Don't know, but I know we had the prior crash, that I don't normally use the weather function (to limit automatic network activity), but figured one more function check on a differenr system would be beneficial.I don't know much about libsoup other than that is is a networking library for GTK applications

**Pull request merged**
