### PR TITLE
Update cities of Kazakhstan.

### PR DESCRIPTION
**Pull request by crayxt**
Hello,
This is the same change from https://bugzilla.gnome.org/show_bug.cgi?id=776493
I've updated the list of Kazakhstan cities.

### CODE REVIEW

**Comment by raveit65** [comment]
Hi,
we create our tarballs with 'make distcheck'.
Unfortunately the PR breaks distcheck
```
[rave@mother libmateweather]$ xmllint --valid --noout data/Locations.xml.in
data/Locations.xml.in:5006: element city: validity error : Element city content does not follow the DTD, expecting ((_name | name+) , coordinates? , zone? , radar? , location+), got (_name coordinates tz-hint location )
      </city>
             ^
data/Locations.xml.in:5017: element city: validity error : Element city content does not follow the DTD, expecting ((_name | name+) , coordinates? , zone? , radar? , location+), got (_name coordinates tz-hint location )
      </city>
             ^
data/Locations.xml.in:5038: element city: validity error : Element city content does not follow the DTD, expecting ((_name | name+) , coordinates? , zone? , radar? , location+), got (_name coordinates tz-hint location )
      </city>
             ^
data/Locations.xml.in:5091: element city: validity error : Element city content does not follow the DTD, expecting ((_name | name+) , coordinates? , zone? , radar? , location+), got (_name coordinates tz-hint location )
      </city>
             ^
data/Locations.xml.in:5104: element city: validity error : Element city content does not follow the DTD, expecting ((_name | name+) , coordinates? , zone? , radar? , location+), got (_name coordinates tz-hint location )
      </city>
             ^
```

**Comment by crayxt** [comment]
OK, I will check

**Comment by crayxt** [comment]
@raveit65 Should be good now, accidentally promoted the tz-hint tag to one level up. Thanks!

**Comment by crayxt** [comment]
Ok, that wasn't an accident - in libgweather tz-hint tag is applied to <city> tag, not <location>. Thanks

**Comment by raveit65** [comment]
squashed and merged to master and 1.18 branch
https://github.com/mate-desktop/libmateweather/commit/aae3bf9f20bceacfb33b2b7006b507dc349979cd
Thank you

**Pull request closed without merging**
