### PR TITLE
rename Europe/Kiev to Europe/Kyiv

### PR DESCRIPTION
**Pull request by mbkma**

### CODE REVIEW

**Comment by lukefromdc** [comment]
This is long overdue given the war

**Review by lukefromdc — COMMENTED** [review]
I found two more places this needs to change in order to show "Kyiv" when adding this city beginning at line 20707:

```
        <!-- The capital of Ukraine.
             "Kiev" is the traditional English name.
             The local name in Ukrainian is "Kyyiv".
          -->
        <name>Kiev</name>
        <coordinates>50.433333 30.516667</coordinates>
```
changes to

```
        <!-- The capital of Ukraine.
             "kyiv" is the traditional English name.
             The local name in Ukrainian is "Kyyiv".
          -->
        <name>kyiv</name>
        <coordinates>50.433333 30.516667</coordinates>
```
Then it works. Install, restart mate-panel and add Kyiv to start
 "kyiv" is the traditional RUSSIAN name for this city...

**Comment by mbkma** [comment]
After this PR is merged, I will release 1.27 of [libmateweather](https://github.com/mate-desktop/libmateweather) and then all repos (finally) are at 1.27.

**Comment by mbkma** [comment]
Anyone else likes to review?

**Comment by XRevan86** [comment]
To throw a shade on the linguistic rationale, English spelling for toponyms does not have to reflect the modern spellings in local languages, and it almost never does (Vienna is not Wein, Rome is not Roma, Moscow is not Moskva, Prague is not Praha). On top of that "Kiev" is not intrinsically Russian as the historic East Slavic name of the city is "Kyyevŭ", or, simplified, "Kyev". However I couldn't verify at what point the loan to English occured, so maybe it was actually from Russian. The Latin spelling is "Kyov" (presumably from Polish), so that's not the origin for the English spelling.  
One could argue that because it's "Kiev" and not "Kyev", it does contain a modern Russian-specific sound change, but that's assuming exact transliteration – unlike Slavic languages English is very willy-nilly about i/y (i.e. [obsolete yland for island](https://en.wiktionary.org/wiki/yland#English)).

But although the word-origins argument is not as strong as some people think the shift gains traction and it's not our place to be prudes about it: upstream (https://github.com/eggert/tz/commit/e13e9c531fc48a04fb8d064acccc9f8ae68d5544) renamed ```Europe/Kiev``` to ```Europe/Kyiv``` and it only makes sense to follow suit.

**Review by XRevan86 — APPROVED** [review]

**Comment by mbkma** [comment]
Moreover, this PR fixes the build which was failing before, see https://app.travis-ci.com/github/mate-desktop/libmateweather/jobs/591004675#L2038

**Review by lukefromdc — APPROVED** [review]
retested with the latest changes, works great now, will merge

**Pull request merged**
