### PR TITLE
Locations: America/Godthab was renamed to America/Nuuk

### LINKED ISSUE #76: FTBFS against tzdata 2020a
#### Expected behaviour

Successful build.

#### Actual behaviour

```
   dh_auto_test
	make -j1 check VERBOSE=1
make[1]: Entering directory '/<<PKGBUILDDIR>>'
Making check in po
make[2]: Entering directory '/<<PKGBUILDDIR>>/po'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/<<PKGBUILDDIR>>/po'
Making check in po-locations
make[2]: Entering directory '/<<PKGBUILDDIR>>/po-locations'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/<<PKGBUILDDIR>>/po-locations'
Making check in libmateweather
make[2]: Entering directory '/<<PKGBUILDDIR>>/libmateweather'
make  check-am
make[3]: Entering directory '/<<PKGBUILDDIR>>/libmateweather'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/<<PKGBUILDDIR>>/libmateweather'
make[2]: Leaving directory '/<<PKGBUILDDIR>>/libmateweather'
Making check in doc
make[2]: Entering directory '/<<PKGBUILDDIR>>/doc'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/<<PKGBUILDDIR>>/doc'
Making check in data
make[2]: Entering directory '/<<PKGBUILDDIR>>/data'

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
xmllint --valid --noout ../data/Locations.xml.in
./check-timezones.sh ./Locations.xml.in
Invalid timezones in ./Locations.xml.in: America/Godthab
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


make[2]: *** [Makefile:637: check] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/data'
make[1]: *** [Makefile:490: check-recursive] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_test: error: make -j1 check VERBOSE=1 returned exit code 2
make: *** [debian/rules:10: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2020-05-22T16:41:15Z
```

#### Steps to reproduce the behaviour

Rebuild libmateweather 1.24.0 on current Debian unstable (containing tzdata 2020a-1).

#### MATE general version

1.24

#### Package version

1.24.0-1

#### Linux Distribution

Debian

#### Link to downstream report of your Distribution

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959545

### PR DESCRIPTION
**Pull request by rbuj**
Closes #76

### CODE REVIEW

**Comment by sc0w** [comment]
The build fails in fedora

`Invalid timezones in ../../../data/Locations.xml.in: America/Nuuk`

@raveit65 

Fedora:latest has fedora 31, maybe the build will be ok in fedora 32 ?

**Comment by raveit65** [comment]
https://hub.docker.com/_/fedora/
I don't know when they change `latest, 31` to `latest, 32`. Fedora 32 is released.
And i don't want to change `latest` to something else only for fixing one build.
Travis Ci should be helper and not a job machine ;)

Any way, this shows that we shouldn't use this PR for stable 1.24 branch for the moment, because fedora 31 and others use mate-1.24 too.
I am sure other distros with 1.24 can also use the old location.
Debian-testing is an unreleased version of debian, so they can use a patch to fix it.
I don't see no reason to break fedora 31 and other released distros with stable 1.24.

**Comment by raveit65** [comment]
Stable libmateweather-1.24.0 builds fine in fedora 32, so changing travis config is useless.

**Comment by raveit65** [comment]
All fedora versions are using tzdata-2020a-1, see https://koji.fedoraproject.org/koji/packageinfo?packageID=50
But debian-testing use tzdata-2020a-1
So, i am still wondering which database is used by the check of `check-timezones.sh`
```
xmllint --valid --noout ../../../data/Locations.xml.in

../../../data/check-timezones.sh ../../../data/Locations.xml.in

Invalid timezones in ../../../data/Locations.xml.in: America/Nuuk
```

When we push this to master than lost option to release tarballs with fedora.
My idea is to install the updated package in travis buildroot to fix fedora build.
But we really need to know was changed in debian/ubuntu/archlinux ?

Any one has an idea?

**Comment by raveit65** [comment]
Found the problem. tzdata-2020a-1 was hanging around in updates-testing for fedora 31.
https://bodhi.fedoraproject.org/updates/FEDORA-2020-f2498da5c3
Should be in stable in a few days.

**Comment by raveit65** [comment]
All travis builds are successful.
I think most distros are using tzdata-2020a-1, including Slackware.
So , it might be save to use this with 1.24.
By the way, the build issue with older  tzdata occurs only during `make distcheck` and not with normal `make` command.
So, i am still wondering why @sunweaver had problems to build his package for debian.

**Pull request merged**
